---

- name: "Ansible: contrib: mkdir folders 1"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ path_tmp_ansible }}"
    - "{{ path_share_ansible }}"

- command: which ansible
  register: cmd_find
- debug:
    msg: "{{ cmd_find |to_yaml }}"

- name: "Ansible: mkdir folders 2"
  file:
    path: "{{ item.dest }}"
    state: directory
  with_flattened:
    - "{{ addon_installs.git }}"
    - "{{ addon_installs.unarchive }}"
    - "{{ addon_installs.get_url }}"

# ------------------------------------------------------------------------------------------------
- include: ./get--ansible-contribs.yml

# ------------------------------------------------------------------------------------------------
- name: "Ansible: download addons (unarchive)"
  unarchive:
    src:   "{{ item.src }}"
    dest:  "{{ item.dest }}"
    mode:  'a+rx'
    copy:  no
    # mode:  "{{ item.mode |default('a+rx') }}"
    # copy:  "{{ item.copy |default(no)     }}"
  with_items: "{{ addon_installs.unarchive }}"

# ------------------------------------------------------------------------------------------------
- name: "Ansible: download addons (git)"
  git:
    repo:    "{{ item.repo }}"
    version: "{{ item.version }}"
    dest:    "{{ item.dest }}"
    depth:   1
    force:   yes
  with_flattened:
    - "{{ addon_installs.git }}"

# ------------------------------------------------------------------------------------------------
- name: "Ansible: download addons (get_url)"
  get_url:
    url:    "{{ item.src }}"
    dest:   "{{ item.dest }}"
    mode:  'a+rx'
    # mode:  "{{ item.mode |default('a+rx') }}"
  with_flattened:
    - "{{ addon_installs.get_url }}"

# ------------------------------------------------------------------------------------------------
- name: "cleanup"
  shell: rm -rf "{{ item }}"
  with_items:
    - "{{ path_tmp_ansible }}"
    - "{{ path_tmp_webcache }}"

