---

path_share_ansible: "/usr/share/ansible"
path_tmp_ansible:   "/tmp/ops/ansible.src"
path_tmp_webcache:  "/tmp/ops/_web_cache"

addon_version:
    "contrib":           "stable-2.2"      # https://github.com/ansible/ansible/tree/devel/contrib
  # "contrib":           "devel"           # https://github.com/ansible/ansible/tree/devel/contrib

    "inv_terraform":
        "adammck":       "0.7-pre"        # https://github.com/adammck/terraform-inventory/releases
        "bandwidthcom":  "0.1.8"           # https://github.com/bandwidthcom/terraform-inventory
        "CiscoCloud":    "master"          # https://github.com/CiscoCloud/terraform.py

    "inv_openstack":
        "lukaspustina":  "master"          # https://github.com/lukaspustina/dynamic-inventory-for-ansible-with-openstack
        "gpaterno":      "master"          # https://github.com/gpaterno/ansible_openstack

addon_installs:
    git:
      - name:    "CiscoCloud"
        repo:    "https://github.com/CiscoCloud/terraform.py"
        version: "{{ addon_version.inv_terraform.CiscoCloud }}"
        dest:    "{{ path_share_ansible }}/inv/terraform--CiscoCloud"

      - name:    "lukaspustina"
        repo:    "https://github.com/lukaspustina/dynamic-inventory-for-ansible-with-openstack"
        version: "{{ addon_version.inv_openstack.lukaspustina }}"
        dest:    "{{ path_share_ansible }}/inv/openstack--lukaspustina"

      - name:   "gpaterno"
        repo:    "https://github.com/gpaterno/ansible_openstack"
        version: "{{ addon_version.inv_openstack.gpaterno }}"
        dest:    "{{ path_share_ansible }}/inv/openstack--gpaterno"

    unarchive:
      - name:   "adammck"
        src:    "https://github.com/adammck/terraform-inventory/releases/download/v{{ addon_version.inv_terraform.adammck }}/terraform-inventory_v{{ addon_version.inv_terraform.adammck }}_linux_amd64.zip"
        dest:   "{{ path_share_ansible }}/inv/terraform--adammck"
        mode:   "a+rx"

    # ruby_gem:
    #   - name:   "bandwidthcom"
    #     gem:    "terraform_inventory"
      # - name:   "bandwidthcom"
      #   src:    "https://github.com/bandwidthcom/terraform-inventory/archive/{{ addon_version.inv_terraform.bandwidthcom }}.zip"
      #   dest:   "{{ path_share_ansible }}/inv/terraform--bandwidthcom"

    get_url: []

# TODO
#       https://github.com/larstobi/terraform-ansible
#       https://github.com/mrcrilly/ansible-inventory-terraform

