---
- hosts: localhost
  # roles:
  #   - role: migibert.terraform
  #     terraform_version: "{{ VERSIONS.terraform }}"
  vars:
    path_tf_bin:        "/usr/local/bin"
    path_share_ansible: "/usr/share/ansible"
    path_tmp_ansible:   "/tmp/ops/ansible.src"
    path_tmp_webcache:  "/tmp/ops/_web_cache"

  vars_files:
    - play-var-versions.yml
    - play-packages.yml

  tasks:
    - include: play-0-apt.yml
    - include: play-3-ansible.yml
    - include: play-5-terraform.yml
    - include: play-9-cleanup.yml
