---
os_add_packages:
  - htop
  - mc
#  - cifs-utils
#  - nfs-utils
#  - awscli

os_add_pip2: []

os_add_pip3:
  - awscli
  #- python-openstackclient

os_add_npm:
  # - gulp-cli
  # - grunt-cli
  - azure-cli
